OPENAI_API_KEY = "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"
EMBEDDING_MODEL = "all-MiniLM-L6-v2"
CHUNK_SIZE = 500
CHUNK_OVERLAP = 50
TOP_K = 5
PDF_PATH = "/Users/sandeep/Downloads/Dummy Data Pdf - Sheet1.csv"
